/*
 * Copyright 2010-2021 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.idea.fir.resolve;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("idea/idea-fir/testData/references/inLibrarySourceFiles")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class FirReferenceResolveInLibrarySourcesTestGenerated extends AbstractFirReferenceResolveInLibrarySourcesTest {
    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
    }

    public void testAllFilesPresentInInLibrarySourceFiles() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("idea/idea-fir/testData/references/inLibrarySourceFiles"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
    }

    @TestMetadata("functionCalls.kt")
    public void testFunctionCalls() throws Exception {
        runTest("idea/idea-fir/testData/references/inLibrarySourceFiles/functionCalls.kt");
    }

    @TestMetadata("javaClasses.kt")
    public void testJavaClasses() throws Exception {
        runTest("idea/idea-fir/testData/references/inLibrarySourceFiles/javaClasses.kt");
    }

    @TestMetadata("referenceToOtherClassesInLib.kt")
    public void testReferenceToOtherClassesInLib() throws Exception {
        runTest("idea/idea-fir/testData/references/inLibrarySourceFiles/referenceToOtherClassesInLib.kt");
    }

    @TestMetadata("stdLib.kt")
    public void testStdLib() throws Exception {
        runTest("idea/idea-fir/testData/references/inLibrarySourceFiles/stdLib.kt");
    }
}
